meta_product_name: "Joombo"
meta_title: "Joombo - The smart handshake"
meta_description: "Joombo is the smart handshake, the contactless digital business card you can instantly share!"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
