meta_product_name: "Joombo"
meta_title: "Joobmo - La première impression avec style"
meta_description: "Joobmo c'est ton magnet indispensable pour que ta première impression soit incroyable"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
